version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-store-nextjs14
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
      - .env.local
    