import { ChangeThemeButton } from '@/ui';
import { Metadata } from 'next';
import styles from './styles.module.scss';

export const metadata: Metadata = {
  title: 'Online store',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className={styles.main}>
      <div><ChangeThemeButton/></div>
    </main>
  );
}
